export const MadLibs = [
  {
    title: 'SICKNOTE',
    story: [
      [
        'Magnus is',
        '$adverb',
        'ill, and won’t be in school today. Last night he ate a very',
        '$adjective',
        'piece of ham, and now his palms are',
        '$adjective',
        ', his tongue is',
        '$color',
        ', and his temperature is a constant',
        '$number',
        'degrees. Please',
        '$verb (present)',
        'for his survival.',
      ],
      ['Have a lovely', '$noun', '!'],
      ['Sincerely,'],
      ["Magnus' mom"],
    ],
  },
  {
    title: 'SHORTCUT',
    story: [
      [
        "If you're trying to get to the library before dark you'll have to cut through the",
        '$adjective',
        'woods. But be careful! There are swarms of',
        '$plural animal',
        "in there and they'll attack anything that",
        '$verb -s',
        '. Take a left at the giant dead',
        '$noun',
        'then',
        '$adverb',
        'walk across the fallen',
        '$noun',
        ". Follow the train tracks into town, just don't walk on the",
        '$adjective',
        "tracks because that's how you die",
      ],
    ],
  },
  {
    title: 'COOKIES',
    story: [
      ['1. Preheat oven to', '$number', 'degrees.'],
      [
        '2. In a',
        '$adjective',
        'bowl, beat butter,',
        '$plural noun',
        ', and eggs on high for 5 minutes.',
      ],
      [
        '3. Add the dry ingredient to the',
        '$adjectvie',
        'ingredients one',
        '$noun',
        'at a time.',
      ],
      ['4.', '$adverb', 'fold in', '$number', 'cups of chocolate chips'],
      ['5. Roll into balls and bake until', '$color', '.'],
    ],
  },
  {
    title: 'CHIPMUNKS',
    story: [
      [
        'Chipmunks are a small',
        '$adjective',
        'rodent capable of surviving',
        '$adjective',
        'winters by stockpiling their food in underground tunnels. Chipmunks have a varied diet consisting of seeds, nuts,',
        '$plural food',
        ', and even small',
        '$plural animal',
        '. Their cheek pouches can hold as many as 12 acorns, 31 corn kernels, or 70',
        '$plural noun',
        '.',
      ],
    ],
  },
  {
    title: 'BREAKFAST CEREAL',
    story: [
      [
        '$noun',
        'puffs are part of a',
        '$adjective',
        'breakfast. Each box contains two whole scoops of ',
        '$plural noun',
        "and a whole day's worth of dietary fiber. Eating our cereal could",
        '$adverb',
        'reduce your risk of',
        '$medical condition',
        '. Nine out of ten',
        '$plural animal',
        'prefer our puffs to the competition!',
      ],
      [
        '*Note: each serving contains',
        '$number',
        'grams of added sugar, and more',
        '$element',
        'than a bowl of ramen. Consume with caution.',
      ],
    ],
  },
];
