export const MadLibs = [
  {
    title: 'SICKNOTE',
    story: [
      [
        'Magnus is',
        'adverb',
        'ill, and won’t be in school today. Last night he ate a very',
        'adjective',
        'piece of ham, and now his palms are',
        'adjective',
        ', his tongue is',
        'color',
        ', and his temperature is a constant',
        'number',
        'degrees. Please',
        'verb',
        'for his survival.',
      ],
      ['Have a lovely', 'noun', '!'],
      ['Sincerely,'],
      ["Magnus' mom"],
    ],
  },
  {
    title: 'SHORTCUT',
    story: [
      [
        'If you want to get to the',
        'place',
        'before dark you’ll have to cut through the',
        'adjective',
        'landfill. But be aware there are three guard',
        'plural noun',
        'so bring something',
        'adjective',
        'for them to eat. Once you’re through the landfill take a left at the giant sculpture of',
        'person',
        'and',
        'verb',
        'under the',
        'adjective',
        'fence. Walk',
        'adverb',
        'through the',
        'adjective',
        'parking lot, and your destination will be to the right.',
      ],
    ],
  },
];
