export const MadLibs = [
  {
    title: 'SICKNOTE',
    story: [
      [
        'Magnus is',
        '$adverb',
        'ill, and won’t be in school today. Last night he ate a very',
        '$adjective',
        'piece of ham, and now his palms are',
        '$adjective',
        ', his tongue is',
        '$color',
        ', and his temperature is a constant',
        '$number',
        'degrees. Please',
        '$verb (present)',
        'for his survival.',
      ],
      ['Have a lovely', '$noun', '!'],
      ['Sincerely,'],
      ["Magnus' mom"],
    ],
  },
  {
    title: 'SHORTCUT',
    story: [
      [
        'If you want to get to the',
        '$place',
        'before dark you’ll have to cut through the',
        '$adjective',
        'landfill. But be aware there are three guard',
        '$plural noun',
        'so bring something',
        '$adjective',
        'for them to eat. Once you’re through the landfill take a left at the giant sculpture of',
        '$person',
        'and',
        '$verb (present)',
        'under the',
        '$adjective',
        'fence. Walk',
        '$adverb',
        'through the',
        '$adjective',
        'parking lot, and your destination will be to the right.',
      ],
    ],
  },
  {
    title: 'COOKIES',
    story: [
      ['1. Preheat oven to', '$number', 'degrees.'],
      [
        '2. In a',
        '$adjective',
        'bowl, beat butter,',
        '$plural noun',
        ', and eggs on high for 5 minutes.',
      ],
      [
        '3. Add the dry ingredient to the',
        '$adjectvie',
        'ingredients one',
        '$noun',
        'at a time.',
      ],
      ['4.', '$adverb', 'fold in', '$number', 'cups of chocolate chips'],
      ['5. Roll into balls and bake until', '$color', '.'],
    ],
  },
  {
    title: 'CHIPMUNKS',
    story: [
      [
        'Chipmunks are a small',
        '$adjective',
        'rodent capable of surviving',
        '$adjective',
        'winters by stockpiling their food in underground tunnels. Chipmunks have a varied diet consisting of seeds, nuts,',
        '$plural food',
        ', and even small',
        '$plural animal',
        '. Their cheek pouches can hold as many as 12 acorns, 31 corn kernels, or 70',
        '$plural noun',
        '.',
      ],
    ],
  },
];
